import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, Bitcoin, Layers, Check, ShieldCheck, Crosshair, GraduationCap, BrainCircuit, ChartNoAxesCombined, ScanLine } from 'lucide-react';
import hero from '@/assets/gnc-markets.jpg';
import { VipButton, SignalsFeed, RouteLink } from '@/components/gnc';
export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: 'GNC SIGNAL — Gold N Crypto. Trade With Precision.' },
    { name: 'description', content: 'Discover Gold and Crypto trading setups, smart money education and a precision-first approach from GOLD N CRYPTO TRADER.' },
    { property: 'og:title', content: 'GNC SIGNAL — Gold N Crypto. Trade With Precision.' },
    { property: 'og:description', content: 'Two markets. One mastery. Explore XAUUSD, BTC and ETH trading education from GNC.' },
    { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' },
  ] }),
  component: Index,
});
function Index() {
  return <>
    <section className="hero"><img className="hero-image" src={hero} width={1920} height={1024} alt="Gold bullion and Bitcoin and Ethereum coins on a black trading desk" fetchPriority="high" /><div className="hero-content"><span className="hero-label"><span className="live-dot" /> GOLD N CRYPTO — TRADE WITH PRECISION</span><h1>Gold N Crypto Signals<br />That Actually <span className="gold-text">Print.</span></h1><p className="hero-description">We don’t sell dreams. We trade with a plan.<br /><strong>XAUUSD, BTC & ETH setups</strong> built on institutional smart money concepts and a relentless focus on precision.</p><div className="hero-buttons"><VipButton market="gold" /><VipButton market="crypto" /></div><p className="hero-risk">Precision is the goal. Profits are never guaranteed.</p></div><div className="hero-market-labels"><div><span>XAUUSD · THE GOLD STANDARD</span><h3>Master Gold.</h3></div><div><span>BTC / ETH · THE NEXT FRONTIER</span><h3>Dominate Crypto.</h3></div></div><div className="hero-bottom"><span><ShieldCheck /> Risk-first strategies</span><span><Crosshair /> Clearly defined setups</span><span><GraduationCap /> Learn. Trade. Evolve.</span></div></section>
    <div className="credentials"><span className="credentials-label">TWO MARKETS.<br />ONE GLOBAL LANGUAGE.</span><strong className="credential-serif">TradingView</strong><strong>MetaTrader 5</strong><strong className="credential-small">₿ BITCOIN</strong><strong className="credential-small">◈ ETHEREUM</strong><span className="demo-label">MARKET ECOSYSTEM · NO AFFILIATION</span></div>
    <section className="section section-centered"><span className="eyebrow">BUILT FOR TRADERS. NOT SPECULATORS.</span><h2>Two markets. <span className="gold-text">One mastery.</span></h2><p className="section-sub">Different markets. The same uncompromising edge.</p><div className="market-grid"><article className="market-card gold"><Layers className="market-watermark" /><div className="market-card-icon"><Layers /></div><h3>The Gold Standard</h3><span className="eyebrow">XAUUSD · SCALPING & SWING</span><ul><li><Check /> London & New York sessions</li><li><Check /> SMC + liquidity concepts</li><li><Check /> Structured pip-based targets</li><li><Check /> Precise entry, SL & TP levels</li></ul><div className="market-card-bottom"><span>DISCIPLINE MEETS OPPORTUNITY</span><VipButton market="gold" compact /></div></article><article className="market-card crypto"><Bitcoin className="market-watermark" /><div className="market-card-icon"><Bitcoin /></div><h3>The Crypto Advantage</h3><span className="eyebrow">BTC & ETH · SPOT & FUTURES</span><ul><li><Check /> High-conviction setups</li><li><Check /> On-chain + technical analysis</li><li><Check /> Structure over speculation</li><li><Check /> Clear risk-to-reward planning</li></ul><div className="market-card-bottom"><span>THE FUTURE FAVORS THE PREPARED</span><VipButton market="crypto" compact /></div></article></div></section>
    <SignalsFeed preview />
    <section className="section features-section"><div className="section-heading"><div><span className="eyebrow">MORE THAN SIGNALS. AN ENTIRE EDGE.</span><h2>Your next level starts here.</h2></div><RouteLink to="/academy">Explore the academy</RouteLink></div><div className="feature-grid">{[{icon:BrainCircuit,title:'GNC AI Tutor',text:'A course-grounded learning companion for Gold and Crypto, with module citations.',tag:'PLANNED · COURSE-GROUNDED AI'},{icon:ScanLine,title:'Instant Chart Analysis',text:'Strategy-aligned entries, stop losses and targets for your Gold and Crypto charts.',tag:'PLANNED · CHART INTELLIGENCE'},{icon:GraduationCap,title:'Learn. Then Earn.',text:'Gold, Crypto and risk-management lessons, with quizzes that sharpen your understanding.',tag:'ACADEMY · SAMPLE QUIZZES'},{icon:ChartNoAxesCombined,title:'Numbers. Not Narratives.',text:'Separate Gold pips and Crypto ROI views. Track the process, not just the outcome.',tag:'PERFORMANCE · DEMO PREVIEW'}].map(f => <div className="feature-item" key={f.title}><f.icon className="feature-icon" size={23} /><h3>{f.title}</h3><p>{f.text}</p><span className="feature-tag">{f.tag}</span></div>)}</div></section>
    <div className="cta-band"><div className="section cta-inner"><div><span className="eyebrow">YOUR EDGE IS A DECISION AWAY</span><h2>Stop chasing. Start trading with precision.</h2><p>Discover the GOLD N CRYPTO TRADER approach.</p></div><VipButton /></div></div>
  </>;
}
