import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { PageIntro } from '@/components/gnc';
import { Button } from '@/components/ui/button';
export const Route = createFileRoute('/performance')({
 head: () => ({ meta: [{ title: 'Performance — GNC SIGNAL' }, { name: 'description', content: 'Preview separate Gold pip and Crypto ROI tracking with clearly labeled illustrative results.' }, { property: 'og:title', content: 'Performance — GNC SIGNAL' }, { property: 'og:description', content: 'Gold pips and Crypto ROI, presented transparently. Sample results are not verified trading performance.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }),
 component: PerformancePage,
});
function PerformancePage() {
 const [market,setMarket] = useState<'gold'|'crypto'>('gold');
 const gold = market === 'gold';
 return <><PageIntro eyebrow="NUMBERS. NOT NARRATIVES." title="The performance perspective." text="Separate markets. Separate metrics. This preview uses illustrative data; audited trading history and third-party verification have not been provided." /><section className="section"><div className="section-heading"><h2>{gold ? 'Gold pips tracker.' : 'Crypto ROI tracker.'}</h2><div className="filter-tabs"><Button variant="ghost" className={gold ? 'selected' : ''} onClick={()=>setMarket('gold')}>Gold · XAUUSD</Button><Button variant="ghost" className={!gold ? 'selected' : ''} onClick={()=>setMarket('crypto')}>Crypto · BTC / ETH</Button></div></div><div className="stats-grid">{[{label:gold?'NET PIPS':'SAMPLE ROI',value:gold?'+428':'+12.8%',sub:'Illustrative monthly result'},{label:'COMPLETED SETUPS',value:gold?'24':'14',sub:'Sample closed trades'},{label:'WIN RATE',value:gold?'83.3%':'78.6%',sub:'Not independently verified'},{label:'AVERAGE RISK / REWARD',value:gold?'1 : 2.8':'1 : 3.1',sub:'Sample setup ratio'}].map(s=><div className="stat" key={s.label}><span>{s.label}</span><strong>{s.value}</strong><small>{s.sub}</small></div>)}</div><div className="performance-chart"><div className="section-heading"><h3>{gold?'Cumulative Gold pips':'Cumulative Crypto ROI'}</h3><span className="demo-label">ILLUSTRATIVE · OCTOBER 2026</span></div><svg viewBox="0 0 1000 240" preserveAspectRatio="none" aria-label="Illustrative cumulative result trend" role="img">{[30,80,130,180,230].map(y=><path key={y} className="chart-grid" d={`M0 ${y} H1000`} />)}<path className="chart-line" d={gold?'M0 220 L50 213 L90 218 L135 185 L175 192 L220 174 L260 180 L300 140 L350 149 L400 135 L440 144 L480 107 L520 118 L560 85 L610 90 L650 74 L700 88 L750 58 L800 65 L850 37 L900 45 L950 20 L1000 12':'M0 220 L70 201 L140 215 L210 172 L280 185 L350 145 L420 160 L490 110 L560 123 L630 85 L700 99 L770 63 L840 71 L910 31 L1000 17'} /></svg><div className="chart-labels"><span>01 OCT</span><span>07 OCT</span><span>14 OCT</span><span>21 OCT</span><span>31 OCT</span></div></div><div className="section-note">Illustrative monthly preview — not an account statement, live tracker or guarantee of future returns.</div><h2 className="mt-10">Closed setups.</h2><div className="table-wrap"><table className="history-table"><thead><tr>{['DATE','PAIR','DIRECTION','RESULT','OUTCOME'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{(gold?[['06 OCT','XAUUSD','BUY','+85 pips','TP2 HIT'],['05 OCT','XAUUSD','SELL','+62 pips','TP1 HIT'],['04 OCT','XAUUSD','BUY','−28 pips','STOP LOSS']]:[['06 OCT','BTCUSD','LONG','+2.34%','TP1 HIT'],['05 OCT','ETHUSD','LONG','+3.10%','TP2 HIT'],['04 OCT','BTCUSD','SHORT','−1.20%','STOP LOSS']]).map(row=><tr key={row[0]}>{row.map((v,i)=><td key={i} className={i===3||i===4?row[4]==='STOP LOSS'?'loss':'profit':''}>{v}</td>)}</tr>)}</tbody></table></div></section></>;
}