import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight, TrendingUp, Menu, X, ArrowRight, ShieldCheck, ChevronRight, Bitcoin, Layers, Check, CircleHelp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { signals, type Market } from '@/lib/markets';
import { LiveTicker } from '@/components/live-ticker';

export function Brand() {
  return <Link to="/" className="brand" aria-label="GNC SIGNAL home"><span className="brand-icon"><TrendingUp size={21} /></span><span><span className="brand-name"><b>GNC</b> SIGNAL</span><span className="brand-sub">GOLD N CRYPTO TRADER</span></span></Link>;
}
export function VipButton({ market = 'all', compact = false }: { market?: Market; compact?: boolean }) {
  const [open, setOpen] = useState(false);
  return <><Button variant={market === 'crypto' ? 'crypto' : 'gold'} size={compact ? 'default' : 'lg'} onClick={() => setOpen(true)}>{compact ? 'Join VIP' : market === 'crypto' ? 'Join Crypto VIP' : market === 'gold' ? 'Join Gold VIP' : 'Explore VIP'}<ArrowUpRight /></Button><Dialog open={open} onOpenChange={setOpen}><DialogContent><span className="eyebrow">THE GNC INNER CIRCLE</span><DialogTitle>Trade with a sharper edge.</DialogTitle><DialogDescription>Contact GOLD N CRYPTO TRADER for {market === 'all' ? 'Gold and Crypto' : market === 'gold' ? 'Gold' : 'Crypto'} membership details, current pricing and availability. No payment is collected on this website.</DialogDescription><ul className="vip-list"><li><Check /> Structured entries, stop losses and targets</li><li><Check /> Gold & crypto market education</li><li><Check /> A risk-first approach to every setup</li></ul><Button variant="gold" asChild><a href="https://www.instagram.com/goldncryptotrader/" target="_blank" rel="noreferrer">Contact @goldncryptotrader <ArrowUpRight /></a></Button><p className="fine-print">Trading involves risk. Profits and accuracy are not guaranteed.</p></DialogContent></Dialog></>;
}
export function Header() {
  const [menu, setMenu] = useState(false);
  const [login, setLogin] = useState(false);
  return <><header className="site-header"><div className="header-inner"><Brand /><nav className={menu ? 'main-nav is-open' : 'main-nav'} aria-label="Main navigation"><Link to="/signals" onClick={() => setMenu(false)} activeProps={{ className: 'active' }}><span className="live-dot" />Live Signals</Link><Link to="/performance" onClick={() => setMenu(false)} activeProps={{ className: 'active' }}>Performance</Link><Link to="/academy" onClick={() => setMenu(false)} activeProps={{ className: 'active' }}>Academy</Link></nav><div className="header-actions"><Button variant="ghost" onClick={() => setLogin(true)} className="login-button">Log in <ArrowUpRight /></Button><VipButton compact /><Button variant="ghost" size="icon" className="mobile-menu" aria-label={menu ? 'Close navigation' : 'Open navigation'} onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</Button></div></div></header><LiveTicker /><Dialog open={login} onOpenChange={setLogin}><DialogContent><DialogTitle>Member access</DialogTitle><DialogDescription>Member sign-in is not connected yet. Contact @goldncryptotrader for VIP access and membership information.</DialogDescription><Button variant="gold" asChild><a href="https://www.instagram.com/goldncryptotrader/" target="_blank" rel="noreferrer">Contact GNC <ArrowUpRight /></a></Button></DialogContent></Dialog></>;
}
export function Footer() {
  return <footer className="site-footer"><div className="footer-top"><Brand /><span>GOLD N CRYPTO — Trade With Precision.</span><a href="https://www.instagram.com/goldncryptotrader/" target="_blank" rel="noreferrer">@goldncryptotrader <ArrowUpRight size={14} /></a></div><div className="footer-bottom"><p>© 2026 GNC SIGNAL. All rights reserved.</p><p>Educational content only. Trading involves substantial risk. Sample results are not verified performance.</p></div></footer>;
}
export function SignalCard({ signal }: { signal: typeof signals[number] }) {
  const [open, setOpen] = useState(false);
  return <><article className={`signal-card ${signal.market}`}><div className="signal-top"><span className="market-badge">{signal.market === 'gold' ? <Layers size={12} /> : <Bitcoin size={12} />}{signal.market.toUpperCase()} SIGNAL</span><span className="signal-time">{signal.time}</span></div><div className="signal-pair"><h3>{signal.pair}</h3><span className="trade-side">{signal.side} <ArrowUpRight size={12} /></span></div><div className="signal-prices"><div><span>ENTRY ZONE</span><b>{signal.entry}</b></div><div><span>STOP LOSS</span><b className="loss">{signal.stop}</b></div></div><div className="targets">{signal.targets.map((target, i) => <div key={target}><span>TP {i + 1}</span><b>{target}</b></div>)}</div><div className="confidence"><span><ShieldCheck size={13} /> Sample AI confidence</span><b>{signal.confidence}%</b></div><div className="confidence-track"><span className={`confidence-fill confidence-${signal.confidence}`} /></div><div className="signal-status"><span><span className="live-dot" />{signal.status}</span><b>{signal.result}</b></div><Button variant="quiet" onClick={() => setOpen(true)} className="analysis-button">View setup analysis <ArrowRight size={14} /></Button></article><Dialog open={open} onOpenChange={setOpen}><DialogContent><span className={`market-badge ${signal.market}`}>{signal.market.toUpperCase()} · SAMPLE SETUP</span><DialogTitle>{signal.pair} {signal.side} analysis</DialogTitle><DialogDescription>{signal.reasoning}</DialogDescription><div className="analysis-levels"><span>Entry <b>{signal.entry}</b></span><span>Stop loss <b className="loss">{signal.stop}</b></span><span>First target <b className="profit">{signal.targets[0]}</b></span></div><p className="fine-print">Illustrative analysis only. This is not a current signal or personalized investment advice.</p></DialogContent></Dialog></>;
}
export function SignalsFeed({ preview = false }: { preview?: boolean }) {
  const [filter, setFilter] = useState<Market>('all');
  return <section className="section signals-section"><div className="section-heading"><div><span className="eyebrow"><span className="live-dot" /> THE MARKET DOESN’T WAIT</span><h2>{preview ? 'Precision in every signal.' : 'Live signals.'}</h2></div>{preview ? <Button variant="quiet" asChild><Link to="/signals">View all signals <ArrowUpRight /></Link></Button> : <div className="filter-tabs" aria-label="Filter signals">{(['all', 'gold', 'crypto'] as const).map(m => <Button key={m} variant="ghost" className={filter === m ? 'selected' : ''} onClick={() => setFilter(m)}>{m === 'all' ? 'All markets' : m === 'gold' ? 'Gold' : 'Crypto'}</Button>)}</div>}</div><div className="signal-grid">{signals.filter(s => filter === 'all' || s.market === filter).map(s => <SignalCard key={s.id} signal={s} />)}</div><div className="section-note"><CircleHelp size={13} /> Demo feed · Prices, confidence scores and outcomes are illustrative, not live market data.</div></section>;
}
export function PageIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="page-intro section"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>; }
export function RouteLink({ to, children }: { to: '/academy' | '/performance' | '/signals'; children: React.ReactNode }) { return <Button variant="quiet" asChild><Link to={to}>{children}<ChevronRight /></Link></Button>; }